name: gluco_care
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

#----------------------PACKAGES-----------------------#
dependencies:
  flutter:
    sdk: flutter

  #Utily Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  lottie: ^3.1.2
  url_launcher: ^6.3.0
  connectivity_plus: ^6.0.3
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4
  flutter_svg: ^2.0.10
  flutter_typeahead: ^5.2.0


  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^4.8.0




#---------------------./ PACKAGE END ---------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  image_path_android: "assets/logos/iconn.png"
  image_path_ios: "assets/logos/iconn.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

flutter:
  uses-material-design: true

#-------------------------LOCAL ASSETS
  assets:
    - assets/logos/
    - assets/images/on_boarding_img/
    - assets/images/verify_img/
    - assets/images/alarma/
    - assets/images/educacion/
 