// lib/src/data/met_values.dart

final Map<String, double> metValues = {
  'Correr (8 km/h)': 8.3,
  'Correr (9.5 km/h)': 9.8,
  'Correr (12 km/h)': 11.8,
  'Caminar (4 km/h)': 3.3,
  'Caminar (5 km/h)': 3.8,
  'Caminar (6 km/h)': 4.3,
  'Bicicleta (lenta)': 4.0,
  'Bicicleta (moderada)': 7.5,
  'Bicicleta (rápida)': 10.0,
  'Natación (lenta)': 6.0,
  'Natación (moderada)': 8.0,
  'Natación (rápida)': 10.3,
  'Yoga': 2.5,
  'Pilates': 3.0,
  'Pesas (ligero)': 3.5,
  'Pesas (intenso)': 6.0,
  'Fútbol': 7.0,
  'Fútbol sala': 8.0,
  'Baloncesto': 6.5,
  'Voleibol': 3.0,
  'Voleibol (competitivo)': 6.0,
  'Tenis (individual)': 8.0,
  'Tenis (dobles)': 6.0,
  'Ping pong': 4.0,
  'Bádminton': 7.0,
  'Escalada (indoor)': 8.0,
  'Escalada (exterior)': 9.0,
  'Bailar (baile libre)': 5.5,
  'Bailar salsa': 6.0,
  'Bailar zumba': 7.5,
  'Bailar tango': 4.5,
  'Saltar la cuerda': 12.3,
  'Senderismo': 6.0,
  'Montañismo': 9.0,
  'Patinaje sobre ruedas': 7.0,
  'Patinaje sobre hielo': 7.0,
  'Esquí alpino': 7.0,
  'Esquí de fondo': 9.0,
  'Snowboard': 6.8,
  'Remo (recreativo)': 5.0,
  'Remo (competitivo)': 8.5,
  'Canoa': 6.0,
  'Kayak': 5.0,
  'Surf': 3.0,
  'Windsurf': 4.0,
  'Boxeo (sombra)': 5.5,
  'Boxeo (entrenamiento)': 6.0,
  'Boxeo (competencia)': 12.8,
  'Artes marciales (karate, judo)': 10.3,
  'Lucha': 8.0,
  'Golf (sin carrito)': 4.3,
  'Golf (con carrito)': 3.5,
  'Equitación': 5.5,
  'Skateboard': 5.0,
  'Esgrima': 6.0,
  'Tai Chi': 3.0,
  'Gimnasia artística': 4.0,
  'Gimnasia aeróbica': 6.0,
  'Step': 8.5,
  'Subir escaleras': 8.8,
  'Bajar escaleras': 3.5,
  'Trotar (5 km/h)': 7.0,
  'Buceo': 7.0,
  'Paseo en moto': 3.5,
  'Paseo en auto (conduciendo)': 2.0,
  'Trabajo de jardinería': 4.0,
  'Cortar césped': 5.5,
  'Palear tierra': 7.5,
  'Limpiar la casa': 3.5,
  'Trapear': 3.5,
  'Lavar el coche': 3.0,
  'Cargar cajas': 6.5,
  'Trabajo de carpintería': 4.5,
  'Pintar paredes': 4.0,
  'Lavar ropa a mano': 4.5,
  'Pescar (de pie)': 3.5,
  'Cazar': 6.5,
  'Corte de leña': 6.3,
  'Cuidar niños (activo)': 3.5,
  'Cuidar niños (sentado)': 2.0,
  'Jugar con niños': 5.0,
  'Cantar de pie': 2.3,
  'Tocar la batería': 4.0,
  'Tocar guitarra (de pie)': 2.3,
  'Tocar piano': 2.3,
  'Coser': 1.5,
  'Pintura artística': 2.0,
  'Estar de pie (inactivo)': 1.8,
  'Sentado (trabajo oficina)': 1.5,
  'Caminata ligera en casa': 2.5,
  'Planchar ropa': 2.3,
  'Hacer compras': 2.5,
  'Cuidar plantas': 2.3,
  'Hacer la cama': 2.3,
  'Reparar bicicleta': 4.0,
  'Limpiar ventanas': 3.0,
  'Ordeñar vacas': 3.5,
  'Cocinar': 2.5,
  'Subir montaña': 9.0,
};

List<String> get metActivitiesList {
  final list = metValues.keys.toList();
  list.sort((a, b) => a.toLowerCase().compareTo(b.toLowerCase()));
  return list;
}