// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYxTdWnB3d7qvy0lUiE-2uLMgUstlqL2A',
    appId: '1:280723908830:web:872e0831746edc5672ba4f',
    messagingSenderId: '280723908830',
    projectId: 'glucocare-305c5',
    authDomain: 'glucocare-305c5.firebaseapp.com',
    storageBucket: 'glucocare-305c5.appspot.com',
    measurementId: 'G-12W3X0GW4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUqkagprPSgoBBa0ZZqKTBECtuLzlDFgk',
    appId: '1:280723908830:android:c2182627dc7924d072ba4f',
    messagingSenderId: '280723908830',
    projectId: 'glucocare-305c5',
    storageBucket: 'glucocare-305c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHUTelWd7-aOI3Z-WD3bavvjwNM4tfQXI',
    appId: '1:280723908830:ios:b1d66496894e2dfe72ba4f',
    messagingSenderId: '280723908830',
    projectId: 'glucocare-305c5',
    storageBucket: 'glucocare-305c5.appspot.com',
    iosBundleId: 'com.example.glucoCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHUTelWd7-aOI3Z-WD3bavvjwNM4tfQXI',
    appId: '1:280723908830:ios:b1d66496894e2dfe72ba4f',
    messagingSenderId: '280723908830',
    projectId: 'glucocare-305c5',
    storageBucket: 'glucocare-305c5.appspot.com',
    iosBundleId: 'com.example.glucoCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYxTdWnB3d7qvy0lUiE-2uLMgUstlqL2A',
    appId: '1:280723908830:web:48704e4a240c103672ba4f',
    messagingSenderId: '280723908830',
    projectId: 'glucocare-305c5',
    authDomain: 'glucocare-305c5.firebaseapp.com',
    storageBucket: 'glucocare-305c5.appspot.com',
    measurementId: 'G-BJFE84XJZ6',
  );
}
